### ISSUE TITLE
armv6l builds

### ISSUE THREAD

**Issue by jareware** [lautis/ruuvitag-listener#1]
Thanks for this lovely utility!

I'm pulling stuff from my RuuviTag's on a Pi Zero W, which is ARMv6. Any change for providing "official" builds for that architecture as well?

If you don't have a Pi Zero or a Pi 1 at hand, [this Docker image](https://hub.docker.com/r/mdirkse/rust_armv6) looks like it would make it easy enough to cross-compile.

**Comment by lautis** [comment]
I don't have a armv6 Raspberry Pi at hand, but [cross has a lot of different architectures supported](https://github.com/rust-embedded/cross#supported-targets). This should work by adding `TARGET=arm-unknown-linux-gnueabihf` to Travis build matrix.

**Comment by lautis** [comment]
@jareware does [this binary](https://paste.lautanala.fi/ruuvitag-listener-p9vTBf4jCNXibq9mxNsoYqB4GOTV8TmRVDUqdQkGaqxffIKs3DLc3j99JkSzVro1Z3qCKlyWc2rHMaDGJzDIsIMJrDjAlt8CtopZ.) work for you?

`arm-unknown-linux-gnueabihf` didn't build but `arm-unknown-linux-gnueabi` did with the rust cross toolchain.

**Comment by jareware** [comment]
It does indeed! I'll replace [my current duct tape](https://github.com/jareware/howto/blob/24508c48abab68594d03f047dfa33883ed17a313/Logging%20values%20from%20a%20RuuviTag.md#reading-values) with this right away. 🎉 

Thanks a lot! ❤️
