### ISSUE TITLE
Always include MAC

### ISSUE THREAD

**Issue by jareware** [lautis/ruuvitag-listener#5]
Having the `--alias` flag is very useful, as Ruuvi's are moved around, and/or replaced. But even when using an alias, also storing the MAC would be nice, to be able to track e.g. battery power per the physical Ruuvi tag, not just its alias.

Would it make sense to include a `mac=12:34...` tag, even when using `--alias`? Or having some `--with-mac` flag to opt in?

Just a thought, I can always keep doing this outside the utility with some `sed` duct tape. 😅

**Comment by lautis** [comment]
Mac could indeed be always included. If we don’t want to have ”extra” fields, then a separate config option for which fields to render could be useful.
