### ISSUE TITLE
Simpler Telegraf configuration

### ISSUE THREAD

**Issue by mikmart** [lautis/ruuvitag-listener#7]
I recently had to re-do my data collection setup, and in the process found a way to simplify the configuration for running RuuviTag Listener with Telegraf. Using the [`execd`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) plugin you could get rid of the `ruuvitag-listener.service` entirely.

In my `ruuvitag.conf` I replaced the socket input and the regex processors with:

```
[[inputs.execd]]
  command = [
    "ruuvitag-listener",
    "--influxdb-measurement", "ruuvitag",
    "--alias", "12:34:56:78:90:AB=Living\\ Room",
    "--alias", "12:34:56:78:90:AC=Bedroom",
    "--alias", "12:34:56:78:90:AD=Office",
  ]
```

I just thought I'd share this approach in case somebody else finds it useful, too.

PS. Thanks for making RuuviTag Listener! I've found it really useful.

**Comment by lautis** [comment]
Thanks! This is indeed quite a bit simpler. Changed example to use this mechanism.
